/**
 * Every run of three to five cards printed in the paid Short Stack PLO
 * product -- the published book (worked hands, example tables, review
 * questions) and the Field Kit's 20-Hand Capstone Quiz -- plus the retired free
 * 3-Hand Reality Check, whose three questions were Capstone questions.
 *
 * Extracted mechanically from the release manuscripts. Card combinations only,
 * no text. Four-card runs are hero holdings, study holdings, or flop-plus-turn
 * boards; three- and five-card runs are boards. The challenge test uses this
 * to prove that no free hand reuses a paid example's holding or flop.
 */

export const paidCardRuns = [
  "9h 8h 6c",
  "9s 8h 2d",
  "9s 8s 3d",
  "9s 8s 7d",
  "Ac Ad Kh",
  "Ac Qd 7s",
  "Ad 7s 2c",
  "As 7d 2c",
  "Jc Td 7s",
  "Js 7d 2c",
  "Js Jd 4h",
  "Js Td 8c",
  "Js Ts 6d",
  "Js Ts 8d",
  "Js Ts 9d",
  "Kc Kd 5s",
  "Ks 8d 3c",
  "Ks Kd 5c",
  "Ks Qs 8d",
  "Qc 7d 4s",
  "Qc Jd Tc",
  "Qd 9c 4s",
  "Qd 9s Ts",
  "Qh 5h 2c",
  "Qh Jh Tc",
  "Qs 8d 3c",
  "Qs 8s 3d",
  "Qs 8s 3s",
  "Qs 9s 4d",
  "Qs 9s 4h",
  "Qs 9s 5d",
  "Qs 9s 6s",
  "Qs 9s 8d",
  "Qs 9s 8s",
  "Ts 8s 3h",
  "6c 6d Kh 2s",
  "9c 9h 8c 7h",
  "9c 9h Ac 2d",
  "9c 9h As Ks",
  "9d 8s Kh 5h",
  "9h 9c Ac 3d",
  "9s 8s 7d 2c",
  "Ac Ad 8s 3h",
  "Ac Kd Js Ts",
  "Ad 9d 9h 8s",
  "Ad 9h 6c 5c",
  "Ah Ac Js Ts",
  "Ah Ac Ks 3d",
  "Ah Kh 7s 6s",
  "Ah Kh Js Ts",
  "Ah Qc Jd 8d",
  "As 5s 6c 3d",
  "As Ad 8h 3c",
  "As Ad Ks Td",
  "As Ad Qc 4c",
  "As Ah 7d 2c",
  "As Ah 8c 3d",
  "As Ah 8d 3c",
  "As Ah Js Th",
  "As Ah Ks Jh",
  "As Ah Ks Kh",
  "As Jh Td 9c",
  "As Js Th 9d",
  "As Kd 8h 3c",
  "As Kd Qc 4h",
  "As Kh Jd Tc",
  "As Ks 7c 6c",
  "As Ks 7h 2c",
  "As Ks 7h 2d",
  "As Ks 7h 3h",
  "As Ks Jd Td",
  "As Ks Jh Th",
  "As Ks Qd Jd",
  "As Ks Qh 3d",
  "As Ks Qh 8h",
  "As Ks Qh Jd",
  "As Ks Qh Jh",
  "As Ks Qs Jd",
  "As Qs Jh 8d",
  "Jc Tc 4h 3h",
  "Jc Tc Kh 2h",
  "Jc Tc Qd 5d",
  "Jd Td 7c 6s",
  "Jh 7h 4s 2s",
  "Jh Jd 4c 3c",
  "Jh Td 9c 9d",
  "Jh Td Ac 3c",
  "Jh Th 9c 8c",
  "Jh Th 9s 8s",
  "Js 7s 4h 2h",
  "Js Ts 4h 2d",
  "Js Ts 7h 6h",
  "Js Ts 9h 8h",
  "Js Ts Ah 2h",
  "Js Ts Ah 3h",
  "Kc Qd 7h 6h",
  "Kd 9c 5s Qh",
  "Kh Kc Qd Jd",
  "Ks Jd 7h 2h",
  "Ks Js Ac 2c",
  "Ks Js Td 8c",
  "Ks Js Th 8h",
  "Ks Kc 8d 7d",
  "Ks Kh 7c 2d",
  "Ks Kh Qs Jh",
  "Ks Kh Qs Qh",
  "Ks Qd 7h 2c",
  "Ks Qs 8d 7d",
  "Ks Qs Jd 9d",
  "Ks Qs Jd Td",
  "Ks Qs Jh Th",
  "Qc Jd 9h 8d",
  "Qc Qd 9h 7h",
  "Qc Qh Jc Th",
  "Qd 9c 4s 8h",
  "Qh Qc 7d 6d",
  "Qh Qd Jc 2c",
  "Qs 9s 4d 7h",
  "Qs 9s 8d 2h",
  "Qs Js Th 9h",
  "Qs Qd 8c 4c",
  "Qs Qd 8h 4h",
  "Tc 9c 7h 6h",
  "Ts 8s Qh 7h",
  "Ts 9s 8h 6h",
  "8c 6d 5s Kh 2c",
  "9c 7d 4s 2c Qc",
  "Ac Ad Kh Ks 2c",
  "Ac Qd 7s 3h 9c",
  "Jd 8d 5c 2s Kh",
  "Ks 9s 4d 8h 2c",
  "Ks Qs 8d 4c 2s",
  "Qs 8s 3d 5h 2s",
  "Qs 9s 4h 2c 6s",
  "Qs 9s 4h 2c 8s",
  "Qs 9s 5d 3c 2s",
  "Qs Ts 7d 2c 3h",
];
